apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        image: lazyyy77/bc:2.6
        ports:
        - containerPort: 8887
