apiVersion: v1
kind: Pod
metadata:
  name: http-proxy
spec:
  containers:
  - name: proxy
    image: yourusername/quiz-proxy  # Replace 'yourusername' with your Docker Hub username
    ports:
    - containerPort: 8888
